### ISSUE TITLE
Call after_transition on a specific transition

### ISSUE THREAD

**Issue by marine44** [geekq/workflow#104]
In the below code, update_stats! runs after every transition. How can I make it only after the a specific transition?

My workflow should work like this:

> Batch.process!
> workflow_state changes to :processing
> .process_batch_items is triggered
> .update_stats! is triggered
> completed_successfully! is called transitioning the batch to :processed

``` ruby
  include Workflow
  workflow do

    state :queued do
      event :process, :transitions_to => :processing
    end

    state :processing do
      event :completed_successfully, :transitions_to => :processed
      event :completed_with_errors, :transitions_to => :processed_with_errors

      after_transition do
        update_stats!
      end

    end

    state :processed_with_errors do
      event :reprocess, :transitions_to => :processing
    end

    state :processed do

    end


  end



  def process
    process_batch_items #? self.completed_successfully! : self.completed_with_errors!
  end

  def update_stats!  
    self.items_processed = self.batch_items.processed.count
    self.save!

    self.items == self.items_processed ? self.completed_successfully! : self.completed_with_errors!
  end

```

**Comment by syntaxTerr0r** [comment]
Hi there, same problem here @ryanharnwell, my neither my `on_state_entry` nor my `on_state_exit` are executed with a similar config. Did you manage to make things works ?

**Comment by jufemaiz** [comment]
@syntaxTerr0r + @ryanharnwell was this ever resolved successfully?

**Comment by tbrammar** [comment]
@ryanharnwell @syntaxTerr0r @ryanharnwell Same issue here. Looking at the code it seems like this functionality was never actually implemented. 

@geekq should it be removed from the readme?

**Comment by tbrammar** [comment]
Please ignore the above comment, I have now got this working using the following format:
```
  def on_[state_name]_entry(*args)
    thing_to_do
  end
```
As defined here: https://github.com/geekq/workflow#new-in-the-version-030
