### ISSUE TITLE
Error: Could not open "'./orders_workflow.png'" for writing

### ISSUE THREAD

**Issue by amejiarosario** [geekq/workflow#110]
```
$ rake doc:workflow MODEL=Order 

Error from ["/usr/bin/dot", "-q1", "-Tpng", "-o'./orders_workflow.png'", "/tmp/graphviz.rb20140724-6086-1i7f866"]:
Error: Could not open "'./orders_workflow.png'" for writing : No such file or directory
/vagrant/lib/tasks/generate_state_machine_diagram.rake:5:in `block (2 levels) in <top (required)>'
Tasks: TOP => doc:workflow
(See full trace by running task with --trace)
```

```
# system: ubuntu-trusty-64 / ruby 2.1.2p95 / Rails 4.0.8
# permissions current directory: drwxr-xr-x 32  501 dialout  1088 Jul 24 16:24 .
```

Any ideas?

**Comment by jkingsbery** [comment]
Also seeing this on MacOS OX 10.9.5, workflow version 1.1. I tried the absolute path, that didn't work.

There error message is a bit confusing: is it trying to write to `'./orders_workflow.png'` or `./orders_workflow.png`, with quotes or without the single quotes?

**Comment by jkingsbery** [comment]
For anyone who cares, patching line 69 of `draw.rb` to be `graph.output options[:format] => "#{filename}"` seems to fix the issue. This is the same change proposed by nyon's PR.

**Comment by geekq** [comment]
I do not use Mac. @jkingsbery can you please test, if the removing single quotes (commit f174a83) helped now?

**Comment by geekq** [comment]
Fails on linux https://travis-ci.org/geekq/workflow/jobs/50497167
Will revert.

**Comment by geekq** [comment]
Will get rid of graph-viz gem. Without that graphviz generation worked reliably for years.

**Comment by rocknruby** [comment]
:+1:

**Comment by loofel** [comment]
applying the fix suggested by  @jkingsbery (_draw.rb:69_ change ```'#{filename}'``` to ```"#{filename}"```) and changing _draw.rb:4_ to ```gem 'ruby-graphviz'#, '~> 1.0.0'``` worked for me on ubuntu trusty

**Comment by rjo** [comment]
has there been any movement on this? I just ran into it again on a new project and can't even remember how i got around it last time.

**Comment by mbhnyc** [comment]
not that got checked in i don't think :(

**Comment by rogerhu** [comment]
See: https://github.com/geekq/workflow/pull/203

**Comment by rogerhu** [comment]
Looks like this fix was patched and then reverted...

**Comment by rogerhu** [comment]
I'm using ```ruby-graphviz (1.2.3) ``` so it seems like there are tests that need be to fixed for this patch to go in?
