### ISSUE TITLE
how to make workflow and paper_trail gem work together?

### ISSUE THREAD

**Issue by warmwater** [geekq/workflow#124]
how to make workflow and paper_trail gem work together?  It seems the changes of workflow_state won't trigger paper_trial

**Comment by omrimos** [comment]
I'm having difficulties implementing that, 
@warmwater - how have you done it? (would be happy for a code sample)

**Comment by cannikin** [comment]
I just ran into something similar. `touch_with_version` wasn't working for me, but this does:

  workflow do
      state :incomplete, :initial => true do
        event :submit, :transitions_to => :approved
      end
      state :approved
      on_transition do
        send(:record_update, true)
      end
    end

So any time there's a transition from one state to another it'll record a version. This records the version BEFORE the new state is saved to the database, which is what we want. 

Found the solution here (although I'm not running master, I'm at 4.0.0.rc1): https://github.com/airblade/paper_trail/issues/508#issuecomment-85639603

**Comment by daveharris** [comment]
What I do is call `update_attribute` for the `workflow_column`:

```ruby
on_transition do |from, to, event, *event_args|
  # Validation is skipped. Callbacks are invoked.
  self.update_attribute(:state, to)
end
```

Seems to work great and seems much less hacky than calling the private `record_update` method

**Comment by daniely** [comment]
@daveharris :+1:

**Comment by jamesmacwilliam** [comment]
I've added https://github.com/geekq/workflow/pull/200 as possible fix for this
