### ISSUE TITLE
Errors Graphing Workflows With  Meta Attributes

### ISSUE THREAD

**Issue by peck** [geekq/workflow#128]
```
ArgumentError: node attribute 'importance' invalid
```

Tracing it down gets to the problem occuring at this line before getting into the graphviz gem:

```
node = graph.add_nodes(to_s, defaults.merge(meta))
```

Digging into the graphviz gem it looks like its raising an error for any attributes that aren't defined for nodes in https://github.com/glejeune/Ruby-Graphviz/blob/6659c3c21060c5c67375642631d9aac284a93149/lib/graphviz/constants.rb

checked by and error raised on line 52 of https://github.com/glejeune/Ruby-Graphviz/blob/6659c3c21060c5c67375642631d9aac284a93149/lib/graphviz/attrs.rb#L51

Looks like non-graphviz node attributes need to be stripped from meta before passing to add_nodes. By changing the line above to:

```
node = graph.add_nodes(to_s, defaults.merge(meta).slice(*GraphViz::Constants.getAttrsFor(/N/).keys.map(&:to_sym)))
```

A bit ugly getting that deep into Graphviz, I think ideally graphviz should have an option to ignore unknown attributes, but seems like that'd be quite a bit into the guts of graphviz and the code explicitly checks for it now. So in the meantime that seems like best workaround?

**Comment by gamov** [comment]
I have the same problem with meta attributes defined on events:
https://github.com/geekq/workflow/blob/master/lib/workflow/event.rb#L31

**Comment by gamov** [comment]
But honestly, to avoid clashes, graphic viz attributes should be in their sub-hash:

    meta: { vg: {label: 'my label', minlen: 23}}

or even their own hash attribute, outside meta

**Comment by joshuaflanagan** [comment]
I think the proper solution is to stop passing the `meta` information to Graphviz. I haven't found any corresponding Graphviz concept for "arbitrary metadata related to this node". The closest I could come up with were "comment" or "tooltip" attributes on a node - but they don't always render.
The fact that *some* `meta` attribute do work is purely by accident/coincidence.
