### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by brandondrew** [geekq/workflow#134]
The README claims:

> You can also access the whole current_state object including the list of possible events and other meta information:

```
article.current_state
=> #<Workflow::State:0x7f1e3d6731f0 @events={
  :submit=>#<Workflow::Event:0x7f1e3d6730d8 @action=nil,
    @transitions_to=:awaiting_review, @name=:submit, @meta={}>},
  name:new, meta{}
```

but in fact, if you follow along with the code snippet-by-snippet in IRB (as the README itself suggests), you not only get a different state, but you don't get an object.  You get a simple string.

```
irb(main):022:0> article.current_state
=> new
```

I'm guessing that there **_is**_ a way to display the Workflow::State object, but it's not used in this part of the README.   Otherwise there must have been a change to the way `current_state` works that didn't get reflected in an update to the README.

**Comment by geekq** [comment]
The output probably depends on the version of irb. My prints the value of `inspect`. You can try it manually:

    article.current_state.inspect

The

    article.current_state.to_s

prints

    => "new"

Are you sure, you get `new` without any quotes?
