### ISSUE TITLE
customize the value of workflow_state column to other than state.to_s ?

### ISSUE THREAD

**Issue by mouazq** [geekq/workflow#136]
Hi, I was just wondering How can I customize the value in database column(workflow_state) to other value different that the symbol name of state:

For example I have
```
  workflow do
    state :not_verified do
      event :verify, :transitions_to => :verified
    end
    state :verified
    state :in_review
    state :deactivated
  end
```

I want :not_verified to be written in database as another value than (:not_verfied.to_s) which is ("not_verfified") for example: ("Not Verified") or any other value, since I have old entries already written and I want to integrate workflow with my current database state !

**Comment by rob-murray** [comment]
Could you run a migration to update existing statuses? I.e. map 'Not Verified' to 'not_verfified', etc

**Comment by asanger** [comment]
@mouazq if you are using rails and you just want to make the state name friendly by removing the underscore, you can use [humanize](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-humanize).

```ruby
# workflow_state is :not_verified
humanize(@user.workflow_state)
# returns 'Not verified'

# if using in a view, you can use
@user.workflow_state.humanize
```

**Comment by mouazq** [comment]
Thanks for your answers guys. unfortunately I am not using workflow anymore, since It's really hard to integrate it with rails_admin
