### ISSUE TITLE
Callbacks for initial state

### ISSUE THREAD

**Issue by jebw** [geekq/workflow#140]
I'm not sure if the following is by design but it does seem counter intuitive.

If an on_state_entry callback is defined for the initial state, then it will _not_ be run when the object initially enters that state, ie it is created.

In my scenario, I have an **Application** model (as in to apply for something) with various states, the first being **unapproved**. The on_unapproved_entry callback should send an email to notify the relevant user to review the Application.

This callback will only be run if the Application goes to another state then returns to **unapproved**. Likewise I can't use a callback on an event since this is an 'automatic' event - ie the transition from _no state_ to **unapproved**.

**Comment by imton** [comment]
@jebw I solved it this way

````
      after_create do
        self.created!
      end

      include Workflow
      workflow_column :state
      workflow do
        state :creating do
          event :created,         transitions_to: :pending
        end
````

**Comment by deemytch** [comment]
+
