### ISSUE TITLE
Inaccurate Readme: Symbols Not Accepted in 1.2.0

### ISSUE THREAD

**Issue by posgarou** [geekq/workflow#145]
The Readme states and gives several examples of using symbols in if: conditions (e.g., `if: :sufficient_battery?`).

However, while the code for this exists in the current [event.rb](https://github.com/geekq/workflow/blob/master/lib/workflow/event.rb#L11-L15), it does not exist in the relevant code for v. 1.2.0, where the same section reads:

```ruby
@condition = if condition.nil? || condition.respond_to?(:call)
                     condition
                   else
                     raise TypeError, 'condition must be nil or callable (eg. a proc or lambda)'
                   end
```

The Readme should either be adjusted or a new version should be released with this feature.

**Comment by geekq** [comment]
From the top of the README:

> Note: you can find documentation for specific workflow rubygem versions at http://rubygems.org/gems/workflow : select a version (optional, default is latest release), click "Documentation" link.

The version on github, master branch is, well, for the master branch ;-) , the upcoming release.

**Comment by geekq** [comment]
P.S. Just extended the note on top of README: 8cfc9ab

**Comment by posgarou** [comment]
Thanks for clarifying!
