### ISSUE TITLE
The Workflow::Event object isn't readily available

### ISSUE THREAD

**Issue by ezuhaib** [geekq/workflow#151]
I expect the following to return an `Workflow::Event` object

```
@article.current_state.events[:publish]
@article.current_state.events.first
```

Whereas both of these return arrays for me, making me have to use:

```
@article.current_state.events[:publish][0]
@article.current_state.events.first[1][0]
```

**Comment by tijmenb** [comment]
`current_state` returns an array of events because there can be multiple events named `publish`. See https://github.com/geekq/workflow/pull/109 for the change that introduced this.

**Comment by jkingsbery** [comment]
I like this idea, would be useful.
