### ISSUE TITLE
Add Ruby 2.2 to the spec?

### ISSUE THREAD

**Issue by mbhnyc** [geekq/workflow#171]
This gem should text against 2.2!  

Also - not seeing much activity here, is this gem still being maintained?  My company relies on it pretty heavily - what's the scoop @geekq?

Thanks!

**Comment by jesperronn** [comment]
Thanks for asking @mbhnyc, I would like to know, too :+1: 

Also, what about ruby 2.3 as well?

@geekq If you are still maintaining, there could probably be an interesting investigation in the Rails5 preparedness. I am not sure if there are any dependencies on rails 5 ?

**Comment by geekq** [comment]
**Workflow 2.0 released!**

Supports Ruby 2.3, 2.4, 2.5 and Rails 5.0, 5.1, 5.2.

Please try it out with your application! If it is a Rails application, please use
https://rubygems.org/gems/workflow-activerecord/versions/4.1.2
Instructions, how to use, are at
https://github.com/geekq/workflow-activerecord#workflow-activerecord

Please report any bugs as a new issue for the relevant of both libraries:
* https://github.com/geekq/workflow/issues
* https://github.com/geekq/workflow-activerecord/issues
