### ISSUE TITLE
Any help available to resolve non supported work flow on PCLaw(XP coded software)

### ISSUE THREAD

**Issue by wantate** [geekq/workflow#180]
I need to retrieve our data from PCLaw software created using I think Windows XP. There is no longer support for the software circa 2003/04 from Lexis Nexis who now own the company.
Any ideas are mostly welcome.

**Comment by geekq** [comment]
This issue tracker is for the Ruby workflow library. Please use a more appropriate place to ask questions about particular software products! http://superuser.com could be suitable.

Closing as offtopic.

**Comment by wantate** [comment]
thanks
