### ISSUE TITLE
Allow one event in any state with same transition

### ISSUE THREAD

**Issue by MathieuDerelle** [geekq/workflow#195]
Is there a way to define an event accessible from any state ?

I've tried 
```
workflow do
  event :invalid, transitions_to: :reject
end 
```
but it doesn't seem to work

If it's not supported now, could it be done in the future please ?

**Comment by geekq** [comment]
1. You can put this line into every state definition

       event :invalid, transitions_to: :reject

2. Or, just define a plain method, so you can call it any time

```ruby
def invalid!
  # do whatever is needed, e.g. depending on `current_state`
  ...

  # persist the rejected state
  persist_workflow_state :reject
end

...
article.invalid!
```

Note on style: I would give a noun name to a state, like `rejected`, not `reject` and give an event a verb name, e.g. `invalidate`.
