### ISSUE TITLE
Can I list all events for a particular state through workflow_spec?

### ISSUE THREAD

**Issue by timeon** [geekq/workflow#196]

**Comment by timeon** [comment]
I ended up with this:

`workflow_spec.states.values.collect(&:events).collect(&:keys).flatten.uniq`

**Comment by dapi** [comment]
All available events: `current_state.events`
All enabled events: `current_state.events.map { |k, events| events.select { |e| e.condition_applicable? self } }.flatten.uniq.map(&:name)`
