### ISSUE TITLE
Could not load the ruby-graphiz or active_support gems for rendering: cannot load such file -- ruby-graphviz

### ISSUE THREAD

**Issue by stefanahman** [geekq/workflow#213]
Hello,

I'm getting the following output when running the specs:

```
Could not load the ruby-graphiz or active_support gems for rendering: cannot load such file -- ruby-graphviz
```

This change (https://github.com/geekq/workflow/commit/3f0c4bb9e1c5fc9e18b122ee86a1aa67490b0cbf#diff-28d45968cd6c27b76bdd91f787ade161) adds a warning every time `ruby-graphviz` cannot be loaded.

Is it possible to skip this warning since it is optional? Quoting:
> Important: If you're interested in graphing your workflow state machine, you will also need to install the activesupport and ruby-graphviz gems.

Thanks!

**Comment by geekq** [comment]
@stefanahman Please try out by referencing the development version

    gem "workflow", git: "git@github.com:geekq/workflow.git", branch: "develop"

**Comment by stefanahman** [comment]
> @stefanahman Please try out by referencing the development version
> 
> ```
> gem "workflow", git: "git@github.com:geekq/workflow.git", branch: "develop"
> ```

I'm still getting the warnings. These warning also applies for `workflow-activerecord`, which is the actual gem that I require in the `Gemfile`.

**Comment by geekq** [comment]
It looks like `rake test` _require_'s all the files in all subfolders. So I now moved `require 'ruby-graphviz'` even deeper into implementation. Please try out the new version @stefanahman  @wingice

**Comment by stefanahman** [comment]
> It looks like `rake test` _require_'s all the files in all subfolders. So I now moved `require 'ruby-graphviz'` even deeper into implementation. Please try out the new version @stefanahman @wingice

Perfect! I got the warning message twice before, now it's shown only once. Please look at
https://github.com/geekq/workflow-activerecord/issues/4
