### ISSUE TITLE
"advanced end to end example" does not exist at given link

### ISSUE THREAD

**Issue by brandonzylstra** [geekq/workflow#215]
The README includes a link labelled "advanced end to end example".  Following this link returns a 404 error.  The URL is https://github.com/geekq/workflow/blob/master/test/advanced_hooks_and_validation_test.rb

**Comment by geekq** [comment]
Advanced, ActiveRecord specific example is better placed in the workflow-activerecord.
So moved to https://github.com/geekq/workflow-activerecord#on_transition
