### ISSUE TITLE
Rake task to draw diagram as Railtie?

### ISSUE THREAD

**Issue by Yuki-Inoue** [geekq/workflow#224]
Currently, the README gives instruction to draw workflow diagram, which gives example implementation of Rake task.

I thought it would be nice if we provide railtie.rb and implement a rake task in there, with something like

```
namespace :workflow do
  desc "Generate a workflow graph"
  task :workflow_draw, ['model_name'] => :environment do |_task, args|
    require 'workflow/draw'
    Workflow::Draw::workflow_diagram(args.model_name.constantize)
  end
end
```
,

It would be useful for all the rails user.

Since it is a Railtie, those who are not using Rails will not be affected, so simply it will just bring benefits to Rails user.

# Question

* How do you say to implementing such railtie code?

If this suggestion looks good, then I can write such Railtie implementation and make PR.

**Comment by geekq** [comment]
`workflow` library is meant to be completely independent of Rails for easier maintenance.
https://github.com/geekq/workflow-activerecord is the home for all workflow and Rails related stuff.

Besides that, I do not know, if everybody needs a `workflow_draw` task in his Rails application. Creating a workflow diagram will be more likely a part of a bigger, application specific documentation generation task and the diagramm will be embedded in some e.g. asciidoctor generated bunch of html files.
