### ISSUE TITLE
previous state?

### ISSUE THREAD

**Issue by chrishough** [geekq/workflow#237]
Before I consider adding a patch to the library, I was curious if we have ever considered having an instance method like `current_state` that would be `previous_state`?

**Comment by geekq** [comment]
Nope, did not consider yet.
If you need it for your use case, you could use the `on_transition` hook https://github.com/geekq/workflow#on_transition to save the previous state to some instance variable.

**Comment by chrishough** [comment]
Thank you @geekq we can use that!
