### ISSUE TITLE
Question: parallelisation state

### ISSUE THREAD

**Issue by nmaisonneuve** [geekq/workflow#26]
since there is no forum, I use the issue tracker for asking a question.

I would like to know if the workflow fit with my requirement 

I have n tasks to complete. A same task need to be parallelised and done by k non-experts , then to aggregated by a reviewer. I would like to design this kind of workflow though the use of this workflow gem as a potential help but I am not sure to understand how to design the parallelisation step.

To get more insights. I need to design a "task assigner" method so that when a non-experts wants a task he can choose on the available tasks that are still in the "parallelised" state  ( less than k   non-experts have completed the task)

nicolas

**Comment by emclab** [comment]
Hi, have you found answer for parallel state? We are looking for ability for parallel event.
