### ISSUE TITLE
Multiple simultaneous workflows

### ISSUE THREAD

**Issue by crystalneth** [geekq/workflow#29]
I like this workflow module, however I'm concerned that it locks me into one state machine per model. The multiple workflow demo appears to be for alternate workflows, not parallel work flows. It's quite possible I would want to add a second unrelated workflow to a model and as far as I can tell this is not possible.

Would love to see:

workflow :billing_state do ...

workflow :activity_state do ...

Not a great example, but basically I like the syntax of this module but may end up using another (such as https://github.com/pluginaweek/state_machine) because this seems like an unnecessary restriction. I haven't looked at the code to see how feasible this would be.

**Comment by numbata** [comment]
+1

**Comment by PanfilovDenis** [comment]
+1
