### ISSUE TITLE
Changing state doesn't update `updated_at`

### ISSUE THREAD

**Issue by jokklan** [geekq/workflow#96]
The title says it all. Is this the expected behaviour (if so why?), and is there a easy way to change this? Also callbacks like `before_update` and `after_update` isn't triggered.

**Comment by srt32** [comment]
If you're using `ActiveRecord` you can override a model method to update both the workflow state column and the timestamp. That change would look something like:

```
  def persist_workflow_state(new_value)
    update_columns(updated_at: Time.current, state: new_value)
  end
```

[This section](https://github.com/geekq/workflow#state-persistence-with-activerecord) of the docs was particularly helpful.
